export const flags: [string, string][] = [
    ["Albánia", "Albania.png"],
    ["Algéria", "Algeria.png"],
    ["Amerikai Szamoa", "American_Samoa.png"],
    ["Andorra", "Andorra.png"],
    ["Angola", "Angola.png"],
    ["Anguilla", "Anguilla.png"],
    ["Antigua és Barbuda", "Antigua_and_Barbuda.png"],
    ["Argentína", "Argentina.png"],
    ["Örményország", "Armenia.png"],
    ["Aruba", "Aruba.png"],
    ["Ausztráila", "Australia.png"],
    ["Ausztria", "Austria.png"],
    ["Azerbajdzsán", "Azerbaijan.png"],
    ["Bahamák", "Bahamas.png"],
    ["Bahrein", "Bahrain.png"],
    ["Banglades", "Bangladesh.png"],
    ["Barbados", "Barbados.png"],
    ["Fehéroroszország", "Belarus.png"],
    ["Belgium", "Belgium.png"],
    ["Belize", "Belize.png"],
    ["Benin", "Benin.png"],
    ["Bermuda", "Bermuda.png"],
    ["Bután", "Bhutan.png"],
    ["Bolívia", "Bolivia.png"],
    ["Bosznia", "Bosnia.png"],
    ["Botswana", "Botswana.png"],
    ["Brazília", "Brazil.png"],
    ["Brit Virgin szigetek", "British_Virgin_Islands.png"],
    ["Brunei", "Brunei.png"],
    ["Bulgária", "Bulgaria.png"],
    ["Burkina Faso", "Burkina_Faso.png"],
    ["Burundi", "Burundi.png"],
    ["Kambodzsa", "Cambodia.png"],
    ["Kamerun", "Cameroon.png"],
    ["Kanada", "Canada.png"],
    ["Zöld-fok", "Cape_Verde.png"],
    ["Kajmán-szigetek", "Cayman_Islands.png"],
    ["Közép-Afrikai Köztársaság", "Central_African_Republic.png"],
    ["Csád", "Chad.png"],
    ["Chile", "Chile.png"],
    ["Kína", "China.png"],
    ["Karácsony-sziget", "Christmas_Island.png"],
    ["Kolumbia", "Colombia.png"],
    ["Comore-szigetek", "Comoros.png"],
    ["Cook-szigetek", "Cook_Islands.png"],
    ["Costa Rica", "Costa_Rica.png"],
    ["Horvátország", "Croatia.png"],
    ["Kuba", "Cuba.png"],
    ["Ciprus", "Cyprus.png"],
    ["Észak-Ciprus", "Cyprus_Northern.png"],
    ["Cseh Köztársaság", "Czech_Republic.png"],
    ["Elefántcsontpart", "Côte_d'Ivoire.png"],
    ["Kongói Demokratikus Köztársaság", "Democratic_Republic_of_the_Congo.png"],
    ["Dánia", "Denmark.png"],
    ["Dzsibuti", "Djibouti.png"],
    ["Dominika", "Dominica.png"],
    ["Dominikai Köztársaság", "Dominican_Republic.png"],
    ["Ekvárod", "Ecuador.png"],
    ["Egyiptom", "Egypt.png"],
    ["El Salvador", "El_Salvador.png"],
    ["Egyenlítői-Guinea", "Equatorial_Guinea.png"],
    ["Eritrea", "Eritrea.png"],
    ["Észtország", "Estonia.png"],
    ["Etiópia", "Ethiopia.png"],
    ["Falkland-szigetek", "Falkland_Islands.png"],
    ["Faroe Szigetek", "Faroe_Islands.png"],
    ["Fiji", "Fiji.png"],
    ["Finnország", "Finland.png"],
    ["Franciaország", "France.png"],
    ["Francia Polinézia", "French_Polynesia.png"],
    ["Gabon", "Gabon.png"],
    ["Gambia", "Gambia.png"],
    ["Grúzia", "Georgia.png"],
    ["Németország", "Germany.png"],
    ["Ghána", "Ghana.png"],
    ["Gibraltár", "Gibraltar.png"],
    ["Görögország", "Greece.png"],
    ["Grönland", "Greenland.png"],
    ["Grenada", "Grenada.png"],
    ["Guam", "Guam.png"],
    ["Guatemala", "Guatemala.png"],
    ["Guinea", "Guinea.png"],
    ["Bissau-Guinea", "Guinea_Bissau.png"],
    ["Guyana", "Guyana.png"],
    ["Haiti", "Haiti.png"],
    ["Honduras", "Honduras.png"],
    ["Hong Kong", "Hong_Kong.png"],
    ["Magyarország", "Hungary.png"],
    ["Izland", "Iceland.png"],
    ["India", "India.png"],
    ["Indonézia", "Indonesia.png"],
    ["Irán", "Iran.png"],
    ["Irak", "Iraq.png"],
    ["Írország", "Ireland.png"],
    ["Izrael", "Israel.png"],
    ["Olaszország", "Italy.png"],
    ["Jamaika", "Jamaica.png"],
    ["Japán", "Japan.png"],
    ["Jordánia", "Jordan.png"],
    ["Kazahsztán", "Kazakhstan.png"],
    ["Kenya", "Kenya.png"],
    ["Kiribati", "Kiribati.png"],
    ["Kuvait", "Kuwait.png"],
    ["Kirgizisztán", "Kyrgyzstan.png"],
    ["Laosz", "Laos.png"],
    ["Lettország", "Latvia.png"],
    ["Libanon", "Lebanon.png"],
    ["Lesotho", "Lesotho.png"],
    ["Libéria", "Liberia.png"],
    ["Líbia", "Libya.png"],
    ["Liechtenstein", "Liechtenstein.png"],
    ["Litvánia", "Lithuania.png"],
    ["Luxemburg", "Luxembourg.png"],
    ["Makaó", "Macao.png"],
    ["Észak-Macedónia", "Macedonia.png"],
    ["Madagaszkár", "Madagascar.png"],
    ["Malawi", "Malawi.png"],
    ["Malajzia", "Malaysia.png"],
    ["Maldív-szigetek", "Maldives.png"],
    ["Mali", "Mali.png"],
    ["Málta", "Malta.png"],
    ["Marshall-szigetek", "Marshall_Islands.png"],
    ["Martinique", "Martinique.png"],
    ["Mauritánia", "Mauritania.png"],
    ["Mauritius", "Mauritius.png"],
    ["Mexikó", "Mexico.png"],
    ["Mikronézia", "Micronesia.png"],
    ["Moldova", "Moldova.png"],
    ["Monaco", "Monaco.png"],
    ["Mongólia", "Mongolia.png"],
    ["Montserrat", "Montserrat.png"],
    ["Marokkó", "Morocco.png"],
    ["Mozambik", "Mozambique.png"],
    ["Mianmar", "Myanmar.png"],
    ["Namíbia", "Namibia.png"],
    ["Nauru", "Nauru.png"],
    ["Nepál", "Nepal.png"],
    ["Hollandia", "Netherlands.png"],
    ["Holland Antillák", "Netherlands_Antilles.png"],
    ["Új-Zéland", "New_Zealand.png"],
    ["Nicaragua", "Nicaragua.png"],
    ["Niger", "Niger.png"],
    ["Nigéria", "Nigeria.png"],
    ["Niue", "Niue.png"],
    ["Norfolk-sziget", "Norfolk_Island.png"],
    ["Észak-Korea", "North_Korea.png"],
    ["Norvégia", "Norway.png"],
    ["Omán", "Oman.png"],
    ["Pakisztán", "Pakistan.png"],
    ["Palau", "Palau.png"],
    ["Panama", "Panama.png"],
    ["Pápua-új-Guinea", "Papua_New_Guinea.png"],
    ["Paraguay", "Paraguay.png"],
    ["Peru", "Peru.png"],
    ["Fülök-szigetek", "Philippines.png"],
    ["Pitcairn-Islands", "Pitcairn_Islands.png"],
    ["Lengyelország", "Poland.png"],
    ["Portugália", "Portugal.png"],
    ["Puerto Rico", "Puerto_Rico.png"],
    ["Katar", "Qatar.png"],
    ["Kongói Köztársaság", "Republic_of_the_Congo.png"],
    ["Románia", "Romania.png"],
    ["Oroszország", "Russian_Federation.png"],
    ["Ruanda", "Rwanda.png"],
    ["Saint Kitts és Nevis", "Saint_Kitts_and_Nevis.png"],
    ["Szamoa", "Samoa.png"],
    ["San Marino", "San_Marino.png"],
    ["Szaud Arábia", "Saudi_Arabia.png"],
    ["Szenegál", "Senegal.png"],
    ["Szerbia és Montenegro", "Serbia_and_Montenegro.png"],
    ["Seychelles-szigetek", "Seychelles.png"],
    ["Sierra Leone", "Sierra_Leone.png"],
    ["Szingapur", "Singapore.png"],
    ["Szlovákia", "Slovakia.png"],
    ["Szlovénia", "Slovenia.png"],
    ["Salamon-szigetek", "Soloman_Islands.png"],
    ["Szomália", "Somalia.png"],
    ["Dél-Afrikai Köztársaság", "South_Africa.png"],
    ["Dél-Georgia", "South_Georgia.png"],
    ["Dél-Korea", "South_Korea.png"],
    ["Szovjet Unió", "Soviet_Union.png"],
    ["Spanyolország", "Spain.png"],
    ["Srí Lanka", "Sri_Lanka.png"],
    ["Szudán", "Sudan.png"],
    ["Suriname", "Suriname.png"],
    ["Szváziföld", "Swaziland.png"],
    ["Svédország", "Sweden.png"],
    ["Svájc", "Switzerland.png"],
    ["Szíria", "Syria.png"],
    ["Taiwan", "Taiwan.png"],
    ["Tádzsikisztán", "Tajikistan.png"],
    ["Tanzánia", "Tanzania.png"],
    ["Thaiföld", "Thailand.png"],
    ["Tibet", "Tibet.png"],
    ["Kelet-Timor", "Timor-Leste.png"],
    ["Togo", "Togo.png"],
    ["Tonga", "Tonga.png"],
    ["Trinidad és Tobago", "Trinidad_and_Tobago.png"],
    ["Tunézia", "Tunisia.png"],
    ["Törökország", "Turkey.png"],
    ["Türkmenisztán", "Turkmenistan.png"],
    ["Turks-és Caicos-szigetek", "Turks_and_Caicos_Islands.png"],
    ["Tuvalu", "Tuvalu.png"],
    ["Egyesült Arab Emírségek", "UAE.png"],
    ["Uganda", "Uganda.png"],
    ["Ukrajna", "Ukraine.png"],
    ["Egyesült Királyság", "United_Kingdom.png"],
    ["Amerikai Egyesült Államok", "United_States_of_America.png"],
    ["Uruguay", "Uruguay.png"],
    ["Amerikai Virgin-szigetek", "US_Virgin_Islands.png"],
    ["Üzbegisztán", "Uzbekistan.png"],
    ["Vanuatu", "Vanuatu.png"],
    ["Vatikán", "Vatican_City.png"],
    ["Venezuela", "Venezuela.png"],
    ["Vietnám", "Vietnam.png"],
    ["Jemen", "Yemen.png"],
    ["Zambia", "Zambia.png"],
    ["Zimbabwe", "Zimbabwe.png"],
];
